<a href="https://colab.research.google.com/github/s1c5000/library_study/blob/main/finish_at_once/Pandas_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas 한번에 제대로 배우기
![image.png]()



---

In [ ]:
import numpy as np
import pandas as pd
pd.__version__

'1.1.5'

## Pandas 객체

### Series 객체

In [ ]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0]) # index와 함께 저장이된다
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [ ]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
s.index # range 형태

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s[1]

0.25

In [ ]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [ ]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index = ['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [ ]:
s['c']

0.5

In [ ]:
s[['c','d','e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [ ]:
'b' in s

True

In [ ]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index=[2,4,6,8, 10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [ ]:
s[4]

0.25

In [ ]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [ ]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
s.value_counts()

1.00    1
0.75    1
0.50    1
0.25    1
0.00    1
dtype: int64

In [ ]:
s.isin([0.25, 0.75]) # 어디에 존재하는지 반환

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [ ]:
pop_tuple = {'서울특별시': 9720846,
             '부산광역시': 3404423,
             '인천광역시': 2747217,
             '대구광역시': 2427954,
             '대전강역시': 1471040,
             '광주광역시': 1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2747217
대구광역시    2427954
대전강역시    1471040
광주광역시    1455048
dtype: int64

In [ ]:
population['서울특별시']

9720846

In [ ]:
population[['서울특별시','부산광역시']]

서울특별시    9720846
부산광역시    3404423
dtype: int64

### DataFrame 객체

In [ ]:
pd.DataFrame([{'A':2, 'B':4, 'D':3},{'A':4, 'B':5,'C':7}]) # 키를 columns로 사용한다, nan 알아서 지정

   A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [ ]:
pd.DataFrame(np.random.rand(5,5),
             columns = ['A','B','C','D','E'],
             index = [1,2,3,4,5])

          A         B         C         D         E
1  0.560690  0.770294  0.124467  0.169349  0.062408
2  0.131537  0.208701  0.375483  0.936749  0.940130
3  0.657155  0.047269  0.165240  0.189086  0.228257
4  0.817795  0.225488  0.898113  0.270797  0.067459
5  0.915788  0.779025  0.059908  0.901007  0.484635

In [ ]:
male_tuple = {'서울특별시': 4732275,
             '부산광역시': 1668618,
             '인천광역시': 1476813,
             '대구광역시': 1198815,
             '대전강역시': 734441,
             '광주광역시': 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전강역시     734441
광주광역시     720060
dtype: int64

In [ ]:
female_tuple = {'서울특별시': 4988571,
             '부산광역시': 1735805,
             '인천광역시': 1470404,
             '대구광역시': 1229139,
             '대전강역시': 736599,
             '광주광역시': 734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전강역시     736599
광주광역시     734988
dtype: int64

In [ ]:
korea_df = pd.DataFrame({'인구수': population,
                         '남자인구수': male,
                         '여자인구수': female,
                         })
korea_df

           인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2747217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전강역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [ ]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전강역시', '광주광역시'], dtype='object')

In [ ]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [ ]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전강역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [ ]:
korea_df['서울특별시':'인천광역시']

           인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2747217  1476813  1470404

### Index 객체
![image.png]()

In [ ]:
idx = pd.Index([2,4,6,8,10]) # 
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [ ]:
idx[1]

4

In [ ]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [ ]:
idx[-1::]

Int64Index([10], dtype='int64')

In [ ]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [ ]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64

#### Index 연산
![image.png]()

In [ ]:
idx1 = pd.Index([1,2,4,6,8])
idx2 = pd.Index([2,4,5,6,7])
print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1 - idx2)
print(idx1.intersection(idx2))
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2)
print(idx1.delete(0)) # index로 접근
print(idx1.drop(1)) # 값으로 접근
print(idx1 ^ idx2) # 여집합

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')



---

## 인덱싱(Indexing)

In [ ]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index = ['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [ ]:
s['b']

0.25

In [ ]:
'b' in s

True

In [ ]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
s.items() # zip으로 묶여서나옴
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [ ]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [ ]:
s['a': 'd'] # index값으로 접근

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [ ]:
s[0:4] # index로 접근

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [ ]:
s[ (s > 0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [ ]:
s[['a','c','e']]

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [ ]:
s = pd.Series(['a','b','c','d','e'],
              index= [1,3,5,7,9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [ ]:
s[1] # 인덱스를 숫자로 줬다. 값으로접근,

'a'

In [ ]:
s[2:4] # 범위가들어가면 인덱스가 수치형이여도 인덱스값으로 가정하는것 같다

5    c
7    d
dtype: object

In [ ]:
s.iloc[1] # 인덱스 번호로접근, Series객체도 iloc가능

'b'

In [ ]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [ ]:
s.reindex(range(10)) # 인덱스 다시부여

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [ ]:
s.reindex(range(10), method='bfill') # method로 nan어떻게 채울지 정할 수 있다. backfill

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱
![image.png]()

In [ ]:
korea_df

           인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2747217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전강역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [ ]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전강역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [ ]:
korea_df.남자인구수

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전강역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [ ]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전강역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [ ]:
korea_df['남여비율'] = korea_df['남자인구수'] * 100 / korea_df['여자인구수']

In [ ]:
korea_df['남여비율']

서울특별시     94.862336
부산광역시     96.129346
인천광역시    100.435867
대구광역시     97.532907
대전강역시     99.707032
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [ ]:
korea_df.values

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.74721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [ ]:
korea_df.T

              서울특별시         부산광역시  ...         대전강역시         광주광역시
인구수    9.720846e+06  3.404423e+06  ...  1.471040e+06  1.455048e+06
남자인구수  4.732275e+06  1.668618e+06  ...  7.344410e+05  7.200600e+05
여자인구수  4.988571e+06  1.735805e+06  ...  7.365990e+05  7.349880e+05
남여비율   9.486234e+01  9.612935e+01  ...  9.970703e+01  9.796895e+01

[4 rows x 6 columns]

In [ ]:
korea_df.values[0]

array([9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [ ]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2747217
대구광역시    2427954
대전강역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [ ]:
korea_df.loc[:'인천광역시', :'남자인구수'] # loc은 고른 행(열) 까지 출력을 해준다. 인덱스로 자르는 것과는 다르다

           인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2747217  1476813

In [ ]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

           인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2747217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [ ]:
korea_df.loc[(korea_df.인구수 < 2000000)]

           인구수   남자인구수   여자인구수       남여비율
대전강역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [ ]:
korea_df.loc[(korea_df.인구수 > 2500000)]

           인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2747217  1476813  1470404  100.435867

In [ ]:
korea_df.loc[(korea_df.남여비율 > 100)]

           인구수    남자인구수    여자인구수        남여비율
인천광역시  2747217  1476813  1470404  100.435867

In [ ]:
korea_df.loc[(korea_df.인구수 > 2500000) & (korea_df.남여비율 > 100)]

           인구수    남자인구수    여자인구수        남여비율
인천광역시  2747217  1476813  1470404  100.435867

In [ ]:
korea_df.iloc[:3, :2]

           인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2747217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [ ]:
korea_df

           인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2747217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전강역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [ ]:
idx_tuples = [('서울특별시', 2010), ('서울특별시', 2020),
              ('부산광역시', 2010), ('부산광역시', 2020),
              ('인천광역시', 2010), ('인천광역시', 2020),
              ('대구광역시', 2010), ('대구광역시', 2020),
              ('대전광역시', 2010), ('대전광역시', 2020),
              ('광주광역시', 2010), ('광주광역시', 2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [ ]:
pop_tuples = [10312545, 9720846,
              2567910, 3404423,
              2758296, 2947217,
              2511676, 2427954,
              1503664, 1471040,
              1454636, 1455048]
population= pd.Series(pop_tuples, index = idx_tuples)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [ ]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [ ]:
population = population.reindex((midx))
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population[:, 2010] # 멀티인덱스일대 첫번재는 상위 두번째가 하위이다.

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [ ]:
population['대전광역시', :] # 멀티인덱스일대 첫번재는 상위 두번째가 하위이다.

2010    1503664
2020    1471040
dtype: int64

In [ ]:
korea_mdf = population.unstack() # 다중인덱스로 만들었던 Series를 일반적인 인덱스로 변환
korea_mdf

           2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [ ]:
korea_mdf.stack() # 다중인덱스를 가진 Series로 변환
korea_mdf

           2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [ ]:
male_tuples = [5111259, 4732275,
              1773170, 1668618,
              1390356, 1476813,
              1255245, 1198815,
              753648, 734441,
              721780, 720060]
male_tuple

{'광주광역시': 720060,
 '대구광역시': 1198815,
 '대전강역시': 734441,
 '부산광역시': 1668618,
 '서울특별시': 4732275,
 '인천광역시': 1476813}

In [ ]:
korea_mdf = pd.DataFrame({
    '총인구수': population,
    '남자인구수' : male_tuples})
korea_mdf

                총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   2567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [ ]:
female_tuples = [5201286, 4988571,
                 1794740, 1735805,
                 1367940, 1470404,
                 1256431, 1229139,
                 750016, 736599,
                 732856, 734988]
female_tuples

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [ ]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples,
                          '여자인구수': female_tuples})
korea_mdf

                총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   2567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [ ]:
ratio = korea_mdf['남자인구수'] * 100/ korea_mdf['여자인구수']
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [ ]:
ratio.unstack()

             2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [ ]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples,
                          '여자인구수': female_tuples,
                          '남여비율': ratio})
korea_mdf

                총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [ ]:
df = pd.DataFrame(np.random.rand(6,3),
                  index=[['a','a','b','b','c','c'], [1,2,1,2,1,2]], # 길이맞춰서 리스트 2개이상주면 멀티인덱스로 만들어줌
                  columns = ['c1','c2','c3'])
df

           c1        c2        c3
a 1  0.736093  0.941433  0.471909
  2  0.456511  0.301596  0.561901
b 1  0.827388  0.617742  0.645722
  2  0.017728  0.283878  0.768098
c 1  0.318680  0.485740  0.925442
  2  0.440673  0.432431  0.564097

In [ ]:
print(pd.MultiIndex.from_arrays([['a','a','b','b','c','c'], [1,2,1,2,1,2]])) # from_arrays로 배열형태를 받아 멀티인덱스 만들기가능
print(pd.MultiIndex.from_tuples([('a',1), ('a',1), ('a',2), ('b', 1), ('b', 2), ('c',1),('c',2)])) # from_tuples로 tuple형태로 받아 멀티인덱스 만들기가능

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )
MultiIndex([('a', 1),
            ('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex.from_product([['a','b','c'], [1,2]]) # 곱해서 만들어줌

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex(levels=[['a','b','c'], [1,2]],
              codes = [[0,0,1,1,2,2], [0,1,0,1,0,1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population.index.names = ['행정구역', '년도'] # 인덱스 이름지정
population

행정구역   년도
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
idx = pd.MultiIndex.from_product([['a','b','c'], [1,2]],
                                 names=['name1', 'name2'])
cols = pd.MultiIndex.from_product([['c1','c2','c3'], [1,2]],
                                  names = ['col_name1','col_name2'])
data = np.round(np.random.randn(6,6), 2)
mdf = pd.DataFrame(data, index=idx, columns = cols)
mdf

col_name1      c1          c2          c3
col_name2       1     2     1     2     1     2
name1 name2
a     1      0.92 -1.29  1.32 -0.39  0.10  0.00
      2     -0.40  0.21 -0.20  0.84  0.44 -0.60
b     1      1.31 -1.45  0.52  1.22  1.03  2.20
      2     -1.02 -0.82  0.40  0.38 -0.86 -1.11
c     1     -0.89 -0.42  0.18  1.71  0.61  0.30
      2     -0.00 -1.24 -0.47  0.38 -0.23 -1.33

In [ ]:
mdf['c2']

col_name2       1     2
name1 name2
a     1      1.32 -0.39
      2     -0.20  0.84
b     1      0.52  1.22
      2      0.40  0.38
c     1      0.18  1.71
      2     -0.47  0.38

#### 인덱싱 및 슬라이싱

In [ ]:
population # Series객체

행정구역   년도
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population['인천광역시', 2010] # Series의 경우 DataFrame처럼 loc, iloc로 접근하지않고 인덱스로 접근가능, DataFrame은 못한다

2758296

In [ ]:
population[:, 2010]

행정구역
서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [ ]:
population[population > 3000000]

행정구역   년도
서울특별시  2010    10312545
       2020     9720846
부산광역시  2020     3404423
dtype: int64

In [ ]:
population[['대구광역시','대전광역시']] # 인덱스의값으로 접근한 것이다

행정구역   년도
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [ ]:
population[[0,4]] # index의 위치값으로도 접근가능

행정구역   년도
서울특별시  2010    10312545
인천광역시  2010     2758296
dtype: int64

In [ ]:
mdf

col_name1      c1          c2          c3
col_name2       1     2     1     2     1     2
name1 name2
a     1      0.92 -1.29  1.32 -0.39  0.10  0.00
      2     -0.40  0.21 -0.20  0.84  0.44 -0.60
b     1      1.31 -1.45  0.52  1.22  1.03  2.20
      2     -1.02 -0.82  0.40  0.38 -0.86 -1.11
c     1     -0.89 -0.42  0.18  1.71  0.61  0.30
      2     -0.00 -1.24 -0.47  0.38 -0.23 -1.33

In [ ]:
mdf['c2',1] # column c2의 1만

name1  name2
a      1        1.32
       2       -0.20
b      1        0.52
       2        0.40
c      1        0.18
       2       -0.47
Name: (c2, 1), dtype: float64

In [ ]:
mdf.iloc[:3, :4]

col_name1      c1          c2
col_name2       1     2     1     2
name1 name2
a     1      0.92 -1.29  1.32 -0.39
      2     -0.40  0.21 -0.20  0.84
b     1      1.31 -1.45  0.52  1.22

In [ ]:
mdf.loc[:,('c2',1)]

name1  name2
a      1        1.32
       2       -0.20
b      1        0.52
       2        0.40
c      1        0.18
       2       -0.47
Name: (c2, 1), dtype: float64

In [ ]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:,2], idx_slice[:,1]] #첫번째위치에 들어가면 행, 두번재에들어가면 열

col_name1      c1    c2    c3
col_name2       1     1     1
name1 name2
a     2     -0.40 -0.20  0.44
b     2     -1.02  0.40 -0.86
c     2     -0.00 -0.47 -0.23

#### 다중 인덱스 재정렬

In [ ]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [ ]:
korea_mdf

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [ ]:
# korea_mdf['서울특별시':'인천광역시'] # error남 정렬이 되지않아서 unsortedIndexError나옴
korea_mdf = korea_mdf.sort_index()
korea_mdf

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [ ]:
korea_mdf['서울특별시':'인천광역시'] # sort해주면 가능
# korea_mdf['서울특별시'] 해주면 keyError남, column을 접근하는 문법과 겹침

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [ ]:
korea_mdf.unstack(level=0) # 0레벨의 인덱스를 unstack

         총인구수                    ...       남여비율
행정구역    광주광역시    대구광역시    대전광역시  ...      부산광역시      서울특별시       인천광역시
년도                               ...
2010  1454636  2511676  1503664  ...  98.798155  98.269140  101.638668
2020  1455048  2427954  1471040  ...  96.129346  94.862336  100.435867

[2 rows x 24 columns]

In [ ]:
korea_mdf.unstack(level=1) # 1레벨의 인덱스를 unstack

           총인구수             남자인구수  ...    여자인구수        남여비율
년도         2010     2020     2010  ...     2020        2010        2020
행정구역                               ...
광주광역시   1454636  1455048   721780  ...   734988   98.488653   97.968946
대구광역시   2511676  2427954  1255245  ...  1229139   99.905606   97.532907
대전광역시   1503664  1471040   753648  ...   736599  100.484256   99.707032
부산광역시   2567910  3404423  1773170  ...  1735805   98.798155   96.129346
서울특별시  10312545  9720846  5111259  ...  4988571   98.269140   94.862336
인천광역시   2758296  2947217  1390356  ...  1470404  101.638668  100.435867

[6 rows x 8 columns]

In [ ]:
korea_mdf.stack().to_frame()

                             0
행정구역  년도
광주광역시 2010 총인구수   1.454636e+06
           남자인구수  7.217800e+05
           여자인구수  7.328560e+05
           남여비율   9.848865e+01
      2020 총인구수   1.455048e+06
           남자인구수  7.200600e+05
           여자인구수  7.349880e+05
           남여비율   9.796895e+01
대구광역시 2010 총인구수   2.511676e+06
           남자인구수  1.255245e+06
           여자인구수  1.256431e+06
           남여비율   9.990561e+01
      2020 총인구수   2.427954e+06
           남자인구수  1.198815e+06
           여자인구수  1.229139e+06
           남여비율   9.753291e+01
대전광역시 2010 총인구수   1.503664e+06
           남자인구수  7.536480e+05
           여자인구수  7.500160e+05
           남여비율   1.004843e+02
      2020 총인구수   1.471040e+06
           남자인구수  7.344410e+05
           여자인구수  7.365990e+05
           남여비율   9.970703e+01
부산광역시 2010 총인구수   2.567910e+06
           남자인구수  1.773170e+06
           여자인구수  1.794740e+06
           남여비율   9.879815e+01
      2020 총인구수   3.404423e+06
           남자인구수  1.668618e+06
           여자인구수  1.735805e+06
           남여비율   9.612935e+01
서울특별시 2010 총인구수   1.031254e+07
           남자인구수  5.111259e+06
           여자인구수  5.201286e+06
           남여비율   9.826914e+01
      2020 총인구수   9.720846e+06
           남자인구수  4.732275e+06
           여자인구수  4.988571e+06
           남여비율   9.486234e+01
인천광역시 2010 총인구수   2.758296e+06
           남자인구수  1.390356e+06
           여자인구수  1.367940e+06
           남여비율   1.016387e+02
      2020 총인구수   2.947217e+06
           남자인구수  1.476813e+06
           여자인구수  1.470404e+06
           남여비율   1.004359e+02

In [ ]:
korea_mdf

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [ ]:
idx_flat = korea_mdf.reset_index(level=0) # reset_index로 멀티인덱스를 평평하게 해준다. level로 기준지정가능
idx_flat

       행정구역      총인구수    남자인구수    여자인구수        남여비율
년도
2010  광주광역시   1454636   721780   732856   98.488653
2020  광주광역시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   2567910  1773170  1794740   98.798155
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10312545  5111259  5201286   98.269140
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [ ]:
idx_flat = korea_mdf.reset_index(level=(0,1)) # 레벨을 전부다 줘버리면 멀티인덱스 사라지고 새로운 인덱스 부여됨, reset_index() 로 인자 안줘도 같은 결과
idx_flat #

     행정구역    년도      총인구수    남자인구수    여자인구수        남여비율
0   광주광역시  2010   1454636   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   2567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312545  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [ ]:
idx_flat.set_index(['행정구역','년도']) # set_index로 index 지정가능, 여러개줘서 멀티인덱스도 가능하다

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

## 데이터 연산

In [ ]:
s =pd.Series(np.random.randint(0,10,size=(5)))
s

0    5
1    9
2    2
3    1
4    8
dtype: int64

In [ ]:
df = pd.DataFrame(np.random.randint(0,10, (3,3)),
                  columns = ['A','B','C'])
df

   A  B  C
0  3  6  3
1  2  2  2
2  4  6  0

In [ ]:
np.exp(s) #e**s

0     148.413159
1    8103.083928
2       7.389056
3       2.718282
4    2980.957987
dtype: float64

In [ ]:
np.cos(df * np.pi/4)

              A             B             C
0 -7.071068e-01 -1.836970e-16 -7.071068e-01
1  6.123234e-17  6.123234e-17  6.123234e-17
2 -1.000000e+00 -1.836970e-16  1.000000e+00

In [ ]:
s1 = pd.Series([1,3,5,7,9], index=[0,1,2,3,4])
s2 = pd.Series([2,4,6,8,10], index=[1,2,3,4,5])
s1 + s2 # index별로 계산, 겹치지않는것은 nan넣음

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [ ]:
s1.add(s2, fill_value=0) # 없는 인덱스에 넣을 값 fill_value로 정할수 있음

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.random.randint(0,20,(3,3)),
                   columns=list('ACD'))
df1

    A   C   D
0   6  15  16
1   1   0  11
2  12   6   8

In [ ]:
df2 = pd.DataFrame(np.random.randint(0,20,(5,5)),
                   columns=list('BAECD'))
df2

    B   A   E   C   D
0  17   9  14   3  17
1  19  12  19   3  14
2   8  12  16  10  11
3   8   1   1   0  18
4  15   0  11  14  16

In [ ]:
df1 + df2

      A   B     C     D   E
0  15.0 NaN  18.0  33.0 NaN
1  13.0 NaN   3.0  25.0 NaN
2  24.0 NaN  16.0  19.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [ ]:
df1.stack()

0  A     6
   C    15
   D    16
1  A     1
   C     0
   D    11
2  A    12
   C     6
   D     8
dtype: int64

In [ ]:
fvalue = df1.stack().mean() # 이런식으로도 많이쓴다
df1.add(df2, fill_value=fvalue)

           A          B          C          D          E
0  15.000000  25.333333  18.000000  33.000000  22.333333
1  13.000000  27.333333   3.000000  25.000000  27.333333
2  24.000000  16.333333  16.000000  19.000000  24.333333
3   9.333333  16.333333   8.333333  26.333333   9.333333
4   8.333333  23.333333  22.333333  24.333333  19.333333

### 연산자 범용 함수
![image.png]()

#### add()

In [ ]:
a = np.random.randint(1,10, size=(3,3))
a

array([[7, 4, 2],
       [2, 5, 3],
       [9, 2, 4]])

In [ ]:
a + a[0] # numpy는 broadcast되서 결과나옴

array([[14,  8,  4],
       [ 9,  9,  5],
       [16,  6,  6]])

In [ ]:
df = pd.DataFrame(a, columns=list('ABC'))
df

   A  B  C
0  7  4  2
1  2  5  3
2  9  2  4

In [ ]:
df + df.iloc[0] # dataframe도 결과가같다.

    A  B  C
0  14  8  4
1   9  9  5
2  16  6  6

In [ ]:
df.add(df.iloc[0])

    A  B  C
0  14  8  4
1   9  9  5
2  16  6  6

#### sub() / subtract()

In [ ]:
a

array([[7, 4, 2],
       [2, 5, 3],
       [9, 2, 4]])

In [ ]:
a - a[0] # broadcast

array([[ 0,  0,  0],
       [-5,  1,  1],
       [ 2, -2,  2]])

In [ ]:
df - df.iloc[0]

   A  B  C
0  0  0  0
1 -5  1  1
2  2 -2  2

In [ ]:
df.sub(df.iloc[0])

   A  B  C
0  0  0  0
1 -5  1  1
2  2 -2  2

In [ ]:
df.subtract(df['B'], axis=0)

   A  B  C
0  3  0 -2
1 -3  0 -2
2  7  0  2

#### mul() / multply()

In [ ]:
a

array([[7, 4, 2],
       [2, 5, 3],
       [9, 2, 4]])

In [ ]:
a * a[1]

array([[14, 20,  6],
       [ 4, 25,  9],
       [18, 10, 12]])

In [ ]:
df

   A  B  C
0  7  4  2
1  2  5  3
2  9  2  4

In [ ]:
df * df.iloc[0]

    A   B  C
0  49  16  4
1  14  20  6
2  63   8  8

In [ ]:
df.mul(df.iloc[0])

    A   B  C
0  49  16  4
1  14  20  6
2  63   8  8

In [ ]:
df.multiply(df.iloc[0])

    A   B  C
0  49  16  4
1  14  20  6
2  63   8  8

#### truediv() /  div() / divide() / floordiv()

In [ ]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [0.28571429, 1.25      , 1.5       ],
       [1.28571429, 0.5       , 2.        ]])

In [ ]:
df

   A  B  C
0  7  4  2
1  2  5  3
2  9  2  4

In [ ]:
df/ df.iloc[0]

          A     B    C
0  1.000000  1.00  1.0
1  0.285714  1.25  1.5
2  1.285714  0.50  2.0

In [ ]:
df.truediv(df.iloc[0])

          A     B    C
0  1.000000  1.00  1.0
1  0.285714  1.25  1.5
2  1.285714  0.50  2.0

In [ ]:
df.divide(df.iloc[0])

          A     B    C
0  1.000000  1.00  1.0
1  0.285714  1.25  1.5
2  1.285714  0.50  2.0

In [ ]:
df.div(df.iloc[0])

          A     B    C
0  1.000000  1.00  1.0
1  0.285714  1.25  1.5
2  1.285714  0.50  2.0

In [ ]:
a// a[0] # 몫

array([[1, 1, 1],
       [0, 1, 1],
       [1, 0, 2]])

In [ ]:
df.floordiv(df.iloc[0]) # 몫

   A  B  C
0  1  1  1
1  0  1  1
2  1  0  2

#### mod()

In [ ]:
a

array([[7, 4, 2],
       [2, 5, 3],
       [9, 2, 4]])

In [ ]:
a % a[0]

array([[0, 0, 0],
       [2, 1, 1],
       [2, 2, 0]])

In [ ]:
df

   A  B  C
0  7  4  2
1  2  5  3
2  9  2  4

In [ ]:
df.mod(df.iloc[0])

   A  B  C
0  0  0  0
1  2  1  1
2  2  2  0

#### pow()

In [ ]:
a

array([[7, 4, 2],
       [2, 5, 3],
       [9, 2, 4]])

In [ ]:
a ** a[0]

array([[ 823543,     256,       4],
       [    128,     625,       9],
       [4782969,      16,      16]])

In [ ]:
df

   A  B  C
0  7  4  2
1  2  5  3
2  9  2  4

In [ ]:
df.pow(df.iloc[0])

         A    B   C
0   823543  256   4
1      128  625   9
2  4782969   16  16

In [ ]:
row = df.iloc[0, ::2] # 두개씩 건너뛰기
row

A    7
C    2
Name: 0, dtype: int64

In [ ]:
df - row

     A   B    C
0  0.0 NaN  0.0
1 -5.0 NaN  1.0
2  2.0 NaN  2.0

### 정렬(Sort)

In [ ]:
s = pd.Series(range(5), index=['A','D','B','C','E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [ ]:
s.sort_index() # index정렬

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [ ]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [ ]:
df = pd.DataFrame(np.random.randint(0,10, (4,4)),
                  index=[2,4,1,3],
                  columns = list('BDAC'))
df

   B  D  A  C
2  3  1  7  7
4  9  6  2  0
1  1  9  3  7
3  1  2  1  8

In [ ]:
df.sort_index() # index 정렬

   B  D  A  C
1  1  9  3  7
2  3  1  7  7
3  1  2  1  8
4  9  6  2  0

In [ ]:
df.sort_index(axis=1) # 1로주면 column이 정렬된다. , sort_column없다.

   A  B  C  D
2  7  3  7  1
4  2  9  0  6
1  3  1  7  9
3  1  1  8  2

In [ ]:
df.sort_values(by='A') # 값을따라서 정렬, 다차원이기때문에 기준 정해야함

   B  D  A  C
3  1  2  1  8
4  9  6  2  0
1  1  9  3  7
2  3  1  7  7

In [ ]:
df.sort_values(by=['A','C']) # A를 우선 정렬한 후 C 를 정렬한다.

   B  D  A  C
3  1  2  1  8
4  9  6  2  0
1  1  9  3  7
2  3  1  7  7

### 순위(Ranking)
![image.png]()

In [ ]:
s = pd.Series([-2,4,7,3,0,7,5,-4,2,6,6,6])
s

0    -2
1     4
2     7
3     3
4     0
5     7
6     5
7    -4
8     2
9     6
10    6
11    6
dtype: int64

In [ ]:
s.rank() # 어느값이 높은지 결과로 나타내줌, 동일한 값이있다면 적당한 수를 정해 순위에 맞게 반환한다.

0      2.0
1      6.0
2     11.5
3      5.0
4      3.0
5     11.5
6      7.0
7      1.0
8      4.0
9      9.0
10     9.0
11     9.0
dtype: float64

In [ ]:
s.rank(method='first') # 같은 데이터가있다면 먼저적힌 순위에따라 순위가 정해짐

0      2.0
1      6.0
2     11.0
3      5.0
4      3.0
5     12.0
6      7.0
7      1.0
8      4.0
9      8.0
10     9.0
11    10.0
dtype: float64

In [ ]:
s.rank(method = 'max') # 같은 값을 갖는 그룹을 높은 값으로지정

0      2.0
1      6.0
2     12.0
3      5.0
4      3.0
5     12.0
6      7.0
7      1.0
8      4.0
9     10.0
10    10.0
11    10.0
dtype: float64

In [ ]:
s.rank(method='min') # 같은 값을 갖는 그룹을 높은 값으로지정

0      2.0
1      6.0
2     11.0
3      5.0
4      3.0
5     11.0
6      7.0
7      1.0
8      4.0
9      8.0
10     8.0
11     8.0
dtype: float64

### 고성능 연산

In [ ]:
nrows, ncols = 100000, 100
df1, df2,df3 ,df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [ ]:
df1.shape

(100000, 100)

In [ ]:
%timeit df1 + df2 + df3 + df4

1 loop, best of 3: 74.8 ms per loop

In [ ]:
%timeit pd.eval('df1 + df2 + df3 + df4') # 고성능연산은 속도가빠르다

10 loops, best of 3: 43.6 ms per loop

In [ ]:
%timeit df1 * -df2 / (-df3 * df4)

10 loops, best of 3: 113 ms per loop

In [ ]:
%timeit pd.eval('df1 * -df2 / (-df3 * df4)')

10 loops, best of 3: 55.4 ms per loop

In [ ]:
%timeit (df1 < df2) & (df2 <= df3) & (df3 != df4)

10 loops, best of 3: 70.9 ms per loop

In [ ]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3) & (df3 != df4)')

10 loops, best of 3: 94.1 ms per loop

In [ ]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns = ['A','B','C','D','E'])
df.head()

          A         B         C         D         E
0  0.982195  0.771480  0.381929  0.631765  0.477668
1  0.061133  0.418054  0.774938  0.608684  0.262282
2  0.465988  0.658973  0.168897  0.407829  0.424226
3  0.914620  0.287418  0.752279  0.844665  0.832384
4  0.703684  0.958661  0.755979  0.202374  0.676584

In [ ]:
%timeit df['A'] + df['B'] / df['C'] - df['D'] * df['E']

10 loops, best of 3: 20.7 ms per loop

In [ ]:
%timeit pd.eval('df.A + df.B / df.C - df.D * df.E')

100 loops, best of 3: 9.3 ms per loop

In [ ]:
%timeit df.eval('A + B / C - D * E') # column명으로 접근해서 계산도 가능

100 loops, best of 3: 15.9 ms per loop

In [ ]:
df.eval('R = A + B / C - D * E', inplace = True) # 계산결과 바로반영도 가능
df.head()

          A         B         C         D         E         R
0  0.982195  0.771480  0.381929  0.631765  0.477668  2.700377
1  0.061133  0.418054  0.774938  0.608684  0.262282  0.440954
2  0.465988  0.658973  0.168897  0.407829  0.424226  4.194592
3  0.914620  0.287418  0.752279  0.844665  0.832384  0.593597
4  0.703684  0.958661  0.755979  0.202374  0.676584  1.834866

In [ ]:
df.eval('R = A - B / C * D * E', inplace = True) # 계산실이바꿔 업데이트도 가능
df.head()

          A         B         C         D         E         R
0  0.982195  0.771480  0.381929  0.631765  0.477668  0.372624
1  0.061133  0.418054  0.774938  0.608684  0.262282 -0.024991
2  0.465988  0.658973  0.168897  0.407829  0.424226 -0.209036
3  0.914620  0.287418  0.752279  0.844665  0.832384  0.645996
4  0.703684  0.958661  0.755979  0.202374  0.676584  0.530051

In [ ]:
col_mean = df.mean(1)
df['A'] + col_mean

0         1.585139
1         0.411150
2         0.785467
3         1.627513
4         1.341573
            ...
999995    0.649872
999996    0.442731
999997    0.774146
999998    0.776808
999999    1.284535
Length: 1000000, dtype: float64

In [ ]:
df.eval('A + @col_mean') # @로 외부에있는 변수를 가져와 계산가능

0         1.585139
1         0.411150
2         0.785467
3         1.627513
4         1.341573
            ...
999995    0.649872
999996    0.442731
999997    0.774146
999998    0.776808
999999    1.284535
Length: 1000000, dtype: float64

In [ ]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]

               A         B         C         D         E         R
1       0.061133  0.418054  0.774938  0.608684  0.262282 -0.024991
8       0.328747  0.197960  0.970480  0.927248  0.002467  0.328281
15      0.342389  0.452474  0.852184  0.354855  0.317540  0.282561
19      0.490851  0.149148  0.621515  0.454503  0.548975  0.430974
45      0.415794  0.087501  0.960324  0.672623  0.859670  0.363108
...          ...       ...       ...       ...       ...       ...
999961  0.253988  0.365877  0.931879  0.011558  0.727367  0.250688
999972  0.004520  0.246775  0.949524  0.211995  0.646477 -0.031098
999981  0.285776  0.267876  0.695310  0.669518  0.413117  0.179217
999987  0.169453  0.251580  0.836197  0.661788  0.527826  0.064359
999997  0.337378  0.388800  0.906696  0.291676  0.409953  0.286104

[124726 rows x 6 columns]

In [ ]:
pd.eval('df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]') # 더 빠름

               A         B         C         D         E         R
1       0.061133  0.418054  0.774938  0.608684  0.262282 -0.024991
8       0.328747  0.197960  0.970480  0.927248  0.002467  0.328281
15      0.342389  0.452474  0.852184  0.354855  0.317540  0.282561
19      0.490851  0.149148  0.621515  0.454503  0.548975  0.430974
45      0.415794  0.087501  0.960324  0.672623  0.859670  0.363108
...          ...       ...       ...       ...       ...       ...
999961  0.253988  0.365877  0.931879  0.011558  0.727367  0.250688
999972  0.004520  0.246775  0.949524  0.211995  0.646477 -0.031098
999981  0.285776  0.267876  0.695310  0.669518  0.413117  0.179217
999987  0.169453  0.251580  0.836197  0.661788  0.527826  0.064359
999997  0.337378  0.388800  0.906696  0.291676  0.409953  0.286104

[124726 rows x 6 columns]

In [ ]:
# 위의 방법이 쓰는게 많아 귀찮으니 query로 질의문 형태로 접근할 수 있다.
df.query('(A < 0.5) and (B < 0.5) and (C > 0.5)') # 이러한 조건이 해당하는 행들을 출력으로 얻고싶으면 eval말고 query 쓰면된다.
# eval은 bool값 리턴한다.

               A         B         C         D         E         R
1       0.061133  0.418054  0.774938  0.608684  0.262282 -0.024991
8       0.328747  0.197960  0.970480  0.927248  0.002467  0.328281
15      0.342389  0.452474  0.852184  0.354855  0.317540  0.282561
19      0.490851  0.149148  0.621515  0.454503  0.548975  0.430974
45      0.415794  0.087501  0.960324  0.672623  0.859670  0.363108
...          ...       ...       ...       ...       ...       ...
999961  0.253988  0.365877  0.931879  0.011558  0.727367  0.250688
999972  0.004520  0.246775  0.949524  0.211995  0.646477 -0.031098
999981  0.285776  0.267876  0.695310  0.669518  0.413117  0.179217
999987  0.169453  0.251580  0.836197  0.661788  0.527826  0.064359
999997  0.337378  0.388800  0.906696  0.291676  0.409953  0.286104

[124726 rows x 6 columns]

In [ ]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B < col_mean)]

               A         B         C         D         E         R
1       0.061133  0.418054  0.774938  0.608684  0.262282 -0.024991
6       0.463837  0.425244  0.221999  0.274273  0.385711  0.261193
7       0.138787  0.024038  0.291059  0.096674  0.988516  0.130894
8       0.328747  0.197960  0.970480  0.927248  0.002467  0.328281
9       0.035235  0.336261  0.287636  0.773722  0.722902 -0.618644
...          ...       ...       ...       ...       ...       ...
999987  0.169453  0.251580  0.836197  0.661788  0.527826  0.064359
999989  0.125136  0.432126  0.040541  0.164522  0.272381 -0.352518
999995  0.261925  0.011120  0.465286  0.896456  0.440409  0.252489
999997  0.337378  0.388800  0.906696  0.291676  0.409953  0.286104
999998  0.463761  0.007763  0.013363  0.770838  0.287570  0.334987

[249501 rows x 6 columns]

In [ ]:
df.query('A < @col_mean and B < @col_mean')

               A         B         C         D         E         R
1       0.061133  0.418054  0.774938  0.608684  0.262282 -0.024991
6       0.463837  0.425244  0.221999  0.274273  0.385711  0.261193
7       0.138787  0.024038  0.291059  0.096674  0.988516  0.130894
8       0.328747  0.197960  0.970480  0.927248  0.002467  0.328281
9       0.035235  0.336261  0.287636  0.773722  0.722902 -0.618644
...          ...       ...       ...       ...       ...       ...
999987  0.169453  0.251580  0.836197  0.661788  0.527826  0.064359
999989  0.125136  0.432126  0.040541  0.164522  0.272381 -0.352518
999995  0.261925  0.011120  0.465286  0.896456  0.440409  0.252489
999997  0.337378  0.388800  0.906696  0.291676  0.409953  0.286104
999998  0.463761  0.007763  0.013363  0.770838  0.287570  0.334987

[249501 rows x 6 columns]

## 데이터 결합

### Concat() / Append()

In [ ]:
s1 = pd.Series(['a','b'], index=[1,2])
s2 = pd.Series(['c','d'], index=[3,5])
pd.concat([s1, s2])

1    a
2    b
3    c
5    d
dtype: object

In [ ]:
def create_df(cols, idx):
  data = {c:[str(c.lower()) + str(i) for i in idx] for c in cols}
  return pd.DataFrame(data, idx)

In [ ]:
df1 = create_df('AB', [1,2])
df1

    A   B
1  a1  b1
2  a2  b2

In [ ]:
df2 = create_df('AB', [3,4])
df2

    A   B
3  a3  b3
4  a4  b4

In [ ]:
pd.concat([df1, df2])

    A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [ ]:
df3 = create_df('AB', [0,1])
df3

    A   B
0  a0  b0
1  a1  b1

In [ ]:
df4 = create_df('CD', [0,1])
df4

    C   D
0  c0  d0
1  c1  d1

In [ ]:
pd.concat([df3, df4]) # 겹치지않는 부분에 대해선 nan삽입

     A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [ ]:
pd.concat([df1, df3])

    A   B
1  a1  b1
2  a2  b2
0  a0  b0
1  a1  b1

In [ ]:
pd.concat([df1, df3], ignore_index=True) # ignore_index를 True로 줘서 인덱스 무시하고 합친다.

    A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [ ]:
pd.concat([df1 , df3], keys=['X','Y']) # 멀티인덱스처럼 X, Y 줄수있다.

      A   B
X 1  a1  b1
  2  a2  b2
Y 0  a0  b0
  1  a1  b1

In [ ]:
df5 = create_df('ABC', [1,2])
df6 = create_df('BCD', [3,4])
pd.concat([df5, df6])

     A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [ ]:
pd.concat([df5, df6], join='inner') # 둘다 존재하는 데이터만 가져온다

    B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [ ]:
df5.append(df6)

     A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [ ]:
pd.concat([df3, df4], axis=1) # axis로 축 지정

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

In [ ]:
pd.concat([df1,df2,df3]) # 여러가지도 가능

    A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4
0  a0  b0
1  a1  b1

### 병합과 조인

In [ ]:
df1 = pd.DataFrame({'학생': ['홍길동','이순신','임꺽정','김유신'],
                    '학과': ['경영학과','교육학과','컴퓨터학과','통계학과']})
df1

    학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [ ]:
df2 = pd.DataFrame({'학생': ['홍길동','이순신','임꺽정','김유신'],
                    '입학년도' : [2012,2016,2019,2020]})
df2

    학생  입학년도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유신  2020

In [ ]:
df3 = pd.merge(df1, df2) # 병합, concat이 합치는것이라면 병합은 열, 행 들이 중복되지않게 합친다
df3

    학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [ ]:
df4 = pd.DataFrame({'학과' : ['경영학과', '교육학과','컴퓨터학과','통계학과'],
                    '학과장' : ['황희','장영실','안창호','정약용']})
df4

      학과  학과장
0   경영학과   황희
1   교육학과  장영실
2  컴퓨터학과  안창호
3   통계학과  정약용

In [ ]:
pd.merge(df3, df4)

    학생     학과  입학년도  학과장
0  홍길동   경영학과  2012   황희
1  이순신   교육학과  2016  장영실
2  임꺽정  컴퓨터학과  2019  안창호
3  김유신   통계학과  2020  정약용

In [ ]:
df5 = pd.DataFrame({'학과' : ['경영학과','교육학과','교육학과','컴퓨터학과','컴퓨터학과','통계학과'],
                    '과목' : ['경영개론','기초수학','물리학','프로그래밍','운영체제','확률론']})
df5

      학과     과목
0   경영학과   경영개론
1   교육학과   기초수학
2   교육학과    물리학
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [ ]:
pd.merge(df1, df5) # 기준이되는 학과를 바탕아르 데이터를 만들다보니 학생이 중복된다.

    학생     학과     과목
0  홍길동   경영학과   경영개론
1  이순신   교육학과   기초수학
2  이순신   교육학과    물리학
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유신   통계학과    확률론

In [ ]:
pd.merge(df1, df2, on='학생') # 기준을 on으로 정할 수 있다. 둘다있는 열로 해야한다.

    학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [ ]:
df6 = pd.DataFrame({'이름': ['홍길동','이순신','임꺽정','김유신'],
                    '성적': ['A','A+','B','A+']})
df6

    이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신  A+

In [ ]:
df1

    학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [ ]:
pd.merge(df1, df6 , left_on= '학생', right_on='이름') # 중복되는 열이 없을경우 left_on, right_on으로 각각 기준 정해줘야한다

    학생     학과   이름  성적
0  홍길동   경영학과  홍길동   A
1  이순신   교육학과  이순신  A+
2  임꺽정  컴퓨터학과  임꺽정   B
3  김유신   통계학과  김유신  A+

In [ ]:
pd.merge(df1,df6, left_on='학생', right_on='이름').drop('이름',axis=1) # drop으로 중복되는 열 지움

    학생     학과  성적
0  홍길동   경영학과   A
1  이순신   교육학과  A+
2  임꺽정  컴퓨터학과   B
3  김유신   통계학과  A+

In [ ]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')

In [ ]:
mdf1

        학과
학생
홍길동   경영학과
이순신   교육학과
임꺽정  컴퓨터학과
김유신   통계학과

In [ ]:
mdf2

     입학년도
학생
홍길동  2012
이순신  2016
임꺽정  2019
김유신  2020

In [ ]:
pd.merge(mdf1, mdf2 , left_index=True, right_index=True) # index를 지정
# pd.merge(mdf1, mdf2) # 그냥하면 지정하라고뜸 :  No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

        학과  입학년도
학생
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [ ]:
mdf1.join(mdf2) # 인덱스를 기준으로 합침

        학과  입학년도
학생
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [ ]:
# left_on, right_on은 기준으로 잡을 열을 정할때 사용
# left_index, right_index는 index를 기준으로 잡아야할때 사용
# 둘다 혼용해서 사용해도 된다
pd.merge(mdf1, df6, left_index=True, right_on='이름')

      학과   이름  성적
0   경영학과  홍길동   A
1   교육학과  이순신  A+
2  컴퓨터학과  임꺽정   B
3   통계학과  김유신  A+

In [ ]:
# 2:06

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)

### GroupBy 연산

### 피벗 테이블(Pivot Table)

### 범주형(Categorical) 데이터

## 문자열 연산

#### 문자열 연산자

#### 기타 연산자

#### 정규표현식

## 시계열 처리

#### 시계열 데이터 구조

### 시계열 기본

### 주기와 오프셋

### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장

### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리

### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly